version: '3.8'

services:
  backend:
    # build 대신 image를 사용합니다. Docker Hub ID와 이미지 이름을 적어주세요.
    image: ${{ secrets.DOCKERHUB_ID }}/scopsreservpj-backend:latest
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: 3306
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    restart: always

  frontend:
    # build 대신 image를 사용합니다. Docker Hub ID와 이미지 이름을 적어주세요.
    image: ${{ secrets.DOCKERHUB_ID }}/scopsreservpj-frontend:latest
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always