# 1단계: Gradle과 JDK 17을 사용하여 소스 코드 빌드
FROM gradle:8.5.0-jdk17 AS build
WORKDIR /app
COPY . .
RUN ./gradlew build -x test

# 2단계: 빌드된 .jar 파일만 가져와서 가벼운 이미지로 만듦
FROM openjdk:17-jdk-slim
WORKDIR /app
COPY --from=build /app/build/libs/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","app.jar"]