# 파일 경로: myProject/projectNameFront/Dockerfile

# 1단계: Node.js를 사용하여 리액트 앱 빌드
FROM node:18 AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# 2단계: 빌드된 결과물을 Nginx 서버에 올림
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
# 이전에 만들었던 nginx.conf 파일을 복사합니다.
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]