name: Deploy Backend to AWS EC2

on:
  push:
    branches: [ "main" ]
    # main 브랜치의 projectNameBack 폴더에 변경이 있을 때만 실행되도록 설정
    paths:
      - 'projectNameBack/**'

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      # 1. GitHub 저장소의 코드를 가져옵니다
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. 백엔드 폴더의 모든 파일을 EC2 서버로 전송합니다
      - name: Deploy to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./projectNameBack/"  # projectNameBack 폴더의 내용물만 전송
          target: "/home/ubuntu/app/backend" # EC2 서버의 배포 디렉토리

      # 3. EC2 서버에 접속해서 백엔드 애플리케이션을 실행합니다 (가장 중요!)
      - name: Run Backend Application on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/app/backend
            # ❗️ 여기에 백엔드 서버를 실행하는 실제 명령어를 입력해야 합니다!
            # 예를 들어, Java라면: java -jar my-backend-app.jar
            # Python(Flask)라면: pm2 restart my-flask-app
            # 우선은 파일 목록만 확인하는 명령어를 넣어두겠습니다.
            ls -al